# Generated by Django 6.0.7 on 2026-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место хранения (стеллаж/ячейка)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
