# Generated by Django 6.0.7 on 2026-07-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/', verbose_name='QR-код'),
        ),
    ]
