# Generated by Django 6.0.7 on 2026-08-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Создан'), ('updated', 'Изменён'), ('photo_added', 'Фото добавлено'), ('quantity_changed', 'Количество изменено'), ('location_changed', 'Местоположение изменено'), ('deleted', 'Удалён')], max_length=20, verbose_name='Тип действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пользователь (кто выполнил действие)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='products.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'История товара',
                'verbose_name_plural': 'История товаров',
                'ordering': ['-created_at'],
            },
        ),
    ]
